### ISSUE TITLE
":" triggers code line to be green even when commented out

### ISSUE THREAD

**Issue by hintron** [Nessphoro/sublimeassembly#16]
The following code shows the problem:

	mov word [0xb8000], 0x4f45 ; E
	mov word [0xb8002], 0x4f52 ; R
	mov word [0xb8004], 0x4f52 ; R
	mov word [0xb8006], 0x4f3a ; :
	mov word [0xb8008], 0x4f20 ; (space)

The third line is colored green incorrectly because of the trailing colon. The colon is commented out, so it shouldn't make the line be colored like a label.

**Comment by hintron** [comment]
Actually, here is the whole code:

	error:
		; Print white text on red background
		mov word [0xb8000], 0x4f45 ; E
		mov word [0xb8002], 0x4f52 ; R
		mov word [0xb8004], 0x4f52 ; R
		mov word [0xb8006], 0x4f3a ; :
		mov word [0xb8008], 0x4f20 ; (space)
		mov byte [0xb800a], al
		mov byte [0xb800b], 0x4f
		hlt

It appears that the error only happens inside a label, and only when indented.

**Comment by hintron** [comment]
![bug](https://cloud.githubusercontent.com/assets/9166578/13302192/e8e82f00-db05-11e5-8cc7-66fea59d89dd.PNG)

**Comment by Nessphoro** [comment]
Thanks, fixed.
The label code was a bit too eager
