### ISSUE TITLE
Build System is useless

### ISSUE THREAD

**Issue by FichteFoll** [Nessphoro/sublimeassembly#21]
Your `selector` should be `"source.assembly"`, because that's what you use in your [syntax definition](https://github.com/Nessphoro/sublimeassembly/blob/master/Assembly%20x86.tmLanguage#L184).

Also, this is how the `file_regex` key works: http://docs.sublimetext.info/en/latest/reference/build_systems/configuration.html#build-capture-error-output

**Comment by Nessphoro** [comment]
Yes you are correct, it was a pull request gone awry.
Will fix as soon as possible, unless you would like to submit a PR yourself?

**Comment by FichteFoll** [comment]
The fault was brought to my attention by someone on IRC. I am merely the messenger.

**Comment by Nessphoro** [comment]
Cool, well I changed it so that now you at least get things such as:
<img width="461" alt="screenshot 2016-11-17 14 38 34" src="https://cloud.githubusercontent.com/assets/2282028/20408662/af97ee98-acd3-11e6-89c6-e70ca0dc5c13.png">
