### ISSUE TITLE
Missing syntax highlighting for many mnemonics

### ISSUE THREAD

**Issue by plestrin** [Nessphoro/sublimeassembly#23]
I noticed that many mnemonics are not correctly handled by syntax highlighting. It concerns at least the following mnemonics:

```asm
adcx
adox
andn
bextr
blsi
blsmsk
blsr
bzhi
clac
clflush
cmpsb
cvtsi2sd
cvttpd2pi
fcomp
fninit
hsubpd
int3
intn
lldt
movdq2q
mulx
pcmpgtb
pcmpgtw
pcmpistrm
phminposuw
pmaddwd
pmuludq
prefetchh
prefetchw
prefetchwt1
punpckhqdq
punpcklqdq
rcl
rdseed
rorx
rsqrtps
sarx
shlx
shrx
stac
tzcnt
vcvtps2ph
vextracti128
vgatherdpd
vgatherdps
vgatherqpd
vgatherqps
vinserti128
vpblendd
vpbroadcast
vperm2i128
vpermd
vpermpd
vpermps
vpermq
vpgatherdd
vpgatherdq
vpgatherqd
vpgatherqq
vpmaskmov
vpsllvd
vpsllvq
vpsravd
vpsrlvd
vpsrlvq
vtestps
xabort
xacquire
xbegin
xend
xrelease
xrstors
xsavec
xsaves
xtest
```
They are either missing or misspelled. In my humble opinion it would be a good idea to check the coherence of the mnemonics in ```instructions.json``` and those in ```Assembly x86.JSON-tmLanguage``` and ```Assembly x86.tmLanguage```

**Comment by Nessphoro** [comment]
Ah, yes.
The TMLanguage was made a long time ago by hand, and the instructions.json was computer generated.
I'll normalize the two, so that the TMLanguage file is generated from the instructions.json
