### ISSUE TITLE
Opening file, while typing

### ISSUE THREAD

**Issue by yazimut** [Nessphoro/sublimeassembly#29]
When I'm trying to write a code in a file, Sublime opens a file, that I'd marked as `%include "file"` in code. When I'm changing the syntax of file (for example, on "Plain text"), it is okay.
My experience: I have a file "PMode entry.asm", in which I had written some code and (at the end of file) directive `%include "func/SetDescriptor.func.asm"`. Since that moment, when I'm trying to type in something in the file "PMode entry.asm", Sublime automatically opens a file "SetDescriptor.func.asm", if it wasn't be opened yet. It is annoying! And, what is interesting, such "openings" happen, only if the file is stored in a directory "func/".

In this 'zip' archive I'd attached my files:
[issue.zip](https://github.com/Nessphoro/sublimeassembly/files/4578295/issue.zip)

**Comment by Nessphoro** [comment]
Opening is fine...but its supposed to close afterwards. At least thats the current behavior until I make it better.
The commit I pushed up should at least make the new window close consistently.
