### ISSUE TITLE
Endif is highlighted, but if, else and elseif are not

### ISSUE THREAD

**Issue by TheWitheredStriker** [Nessphoro/sublimeassembly#31]
Hello there.

Something I've noticed, and that bugs me a bit, is that this grammar appears to highlight the `endif` keyword just fine, but doesn't cover `if`, `else` and `elseif`. Or at the very least, this is the case on GitHub, where this grammar is used in Linguist for syntax highlighting.

Example:
![image](https://user-images.githubusercontent.com/38614982/199688573-42f23d46-e449-4174-8159-597395c7b1ba.png)
From <https://github.com/Ralakimus/sonic-cd-disassembly/blob/main/Main.asm>

Another:
![image](https://user-images.githubusercontent.com/38614982/199688733-6523e134-d424-4a4c-9067-f11eabff0f0b.png)
From <https://github.com/sonicretro/s1disasm/blob/AS/sonic.asm>

I should mention that both of those repos use Motorola 68k ASM.

Regardless, it seems bizarre to me that the grammar doesn't highlight if, else and elseif, but _does_ highlight endif. Could someone perhaps look into this?

**Comment by Nessphoro** [comment]
Interesting, this particular package only targets NASM syntax specifically I wouldn't have expected it to highlight endif and to instead treat it as a label (like it does with the rest of "unknown" symbols i.e. `if` `else`).

Indeed Sublime Text renders it correctly:
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/2282028/204954359-f3bf03ab-ebbb-4097-893d-83f18e73c0ce.png">

So I do wonder if its something specifically off with 1) the version that Github picked up or 2) the renderer / parser that they use.

**Comment by Nessphoro** [comment]
I think for m68k the highlighting is provided by https://github.com/zerkman/language-m68k, and it seems to be the issue is coming from there.

**Comment by TheWitheredStriker** [comment]
Alright, thanks! I'll raise an issue there.
